### ISSUE TITLE
Is "COVID-19 genome" a correct description? 

### ISSUE THREAD

**Issue by jgehrcke** [galaxyproject/SARS-CoV-2#48]
The repo README contains "COVID-19 genome".

As far as I understand "COVID-19" is the name for the disease. Should this be `SARS-CoV-2` genome instead?

**Comment by ssb22** [comment]
Or `SARS-CoV-2 genome that causes COVID-19` so it can be searched using both keywords?

**Comment by ssb22** [comment]
Or `SARS-CoV-2 genome that causes COVID-19` so it can be searched using both keywords?

**Comment by bgruening** [comment]
@ssb22 I like that. Does anyone of you want to make this change or should I? You get then listed as committer :)

**Comment by ssb22** [comment]
Sorry I accidentally deleted my comment due to browser issues.  I suggested `SARS-CoV-2 genome that causes COVID-19` so it can be searched on both keywords, but come to think of it `COVID-19` is mentioned in reasonable proximity anyway so we might as well keep the link briefer by saying `SARS-CoV-2 genome`.  I've submitted a pull request.

**Comment by bgruening** [comment]
Thanks both for the catch!

**Comment by jgehrcke** [comment]
Collaboration can be really cool. Thanks :)
